[rospy.client][INFO] 2019-12-05 00:03:06,836: init_node, name[/edrone/spawn_edrone], pid[3720]
[xmlrpc][INFO] 2019-12-05 00:03:06,837: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2019-12-05 00:03:06,837: Started XML-RPC server [http://itachi-HP-Pavilion-Laptop-15-cc1xx:42791/]
[rospy.init][INFO] 2019-12-05 00:03:06,837: ROS Slave URI: [http://itachi-HP-Pavilion-Laptop-15-cc1xx:42791/]
[rospy.impl.masterslave][INFO] 2019-12-05 00:03:06,838: _ready: http://itachi-HP-Pavilion-Laptop-15-cc1xx:42791/
[rospy.registration][INFO] 2019-12-05 00:03:06,839: Registering with master node http://localhost:11311
[xmlrpc][INFO] 2019-12-05 00:03:06,839: xml rpc node: starting XML-RPC server
[rospy.init][INFO] 2019-12-05 00:03:06,938: registered with master
[rospy.rosout][INFO] 2019-12-05 00:03:06,938: initializing /rosout core topic
[rospy.rosout][INFO] 2019-12-05 00:03:06,941: connected to core topic /rosout
[rospy.simtime][INFO] 2019-12-05 00:03:06,943: initializing /clock core topic
[rospy.simtime][INFO] 2019-12-05 00:03:06,946: connected to core topic /clock
[rosout][INFO] 2019-12-05 00:03:06,953: Loading model XML from ros parameter
[rosout][INFO] 2019-12-05 00:03:06,961: Waiting for service /gazebo/spawn_urdf_model
[rospy.internal][INFO] 2019-12-05 00:03:07,191: topic[/rosout] adding connection to [/rosout], count 0
[rosout][INFO] 2019-12-05 00:03:07,567: Calling service /gazebo/spawn_urdf_model
[rospy.internal][INFO] 2019-12-05 00:03:07,623: topic[/clock] adding connection to [http://itachi-HP-Pavilion-Laptop-15-cc1xx:40623/], count 0
[rosout][INFO] 2019-12-05 00:03:08,019: Spawn status: SpawnModel: Successfully spawned entity
[rospy.core][INFO] 2019-12-05 00:03:08,020: signal_shutdown [atexit]
[rospy.internal][INFO] 2019-12-05 00:03:08,023: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2019-12-05 00:03:08,024: topic[/clock] removing connection to http://itachi-HP-Pavilion-Laptop-15-cc1xx:40623/
[rospy.topics][ERROR] 2019-12-05 00:03:08,025: Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 326, in close
    c.close()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 838, in close
    self.socket.close()
AttributeError: 'NoneType' object has no attribute 'close'

[rospy.impl.masterslave][INFO] 2019-12-05 00:03:08,025: atexit
[rospy.internal][WARNING] 2019-12-05 00:03:08,025: Unknown error initiating TCP/IP socket to itachi-HP-Pavilion-Laptop-15-cc1xx:40029 (http://itachi-HP-Pavilion-Laptop-15-cc1xx:40623/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
AttributeError: 'NoneType' object has no attribute 'buff_size'

