[rospy.client][INFO] 2020-02-28 16:08:47,887: init_node, name[/rostopic_15837_1582886327830], pid[15837]
[xmlrpc][INFO] 2020-02-28 16:08:47,890: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2020-02-28 16:08:47,891: Started XML-RPC server [http://itachi-HP-Pavilion-Laptop-15-cc1xx:36883/]
[rospy.init][INFO] 2020-02-28 16:08:47,892: ROS Slave URI: [http://itachi-HP-Pavilion-Laptop-15-cc1xx:36883/]
[rospy.impl.masterslave][INFO] 2020-02-28 16:08:47,892: _ready: http://itachi-HP-Pavilion-Laptop-15-cc1xx:36883/
[rospy.registration][INFO] 2020-02-28 16:08:47,896: Registering with master node http://localhost:11311
[xmlrpc][INFO] 2020-02-28 16:08:47,896: xml rpc node: starting XML-RPC server
[rospy.init][INFO] 2020-02-28 16:08:47,994: registered with master
[rospy.rosout][INFO] 2020-02-28 16:08:47,994: initializing /rosout core topic
[rospy.rosout][INFO] 2020-02-28 16:08:47,996: connected to core topic /rosout
[rospy.simtime][INFO] 2020-02-28 16:08:47,998: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2020-02-28 16:08:48,067: topic[/stats_sr] adding connection to [http://itachi-HP-Pavilion-Laptop-15-cc1xx:36987/], count 0
[rospy.internal][INFO] 2020-02-28 16:08:48,261: topic[/rosout] adding connection to [/rosout], count 0
[rospy.core][INFO] 2020-02-28 16:09:49,563: signal_shutdown [signal-2]
[rospy.internal][INFO] 2020-02-28 16:09:49,567: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2020-02-28 16:09:49,568: topic[/stats_sr] removing connection to http://itachi-HP-Pavilion-Laptop-15-cc1xx:36987/
[rospy.internal][WARNING] 2020-02-28 16:09:49,569: Unknown error initiating TCP/IP socket to itachi-HP-Pavilion-Laptop-15-cc1xx:45943 (http://itachi-HP-Pavilion-Laptop-15-cc1xx:36987/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
AttributeError: 'NoneType' object has no attribute 'buff_size'

[rospy.topics][ERROR] 2020-02-28 16:09:49,569: Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 326, in close
    c.close()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 838, in close
    self.socket.close()
AttributeError: 'NoneType' object has no attribute 'close'

[rospy.impl.masterslave][INFO] 2020-02-28 16:09:49,569: signal-2
[rospy.core][INFO] 2020-02-28 16:09:49,674: signal_shutdown [atexit]
