[rospy.client][INFO] 2020-01-31 17:20:18,690: init_node, name[/sr_determine_rois_5623_1580471418643], pid[5623]
[xmlrpc][INFO] 2020-01-31 17:20:18,690: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2020-01-31 17:20:18,691: Started XML-RPC server [http://itachi-HP-Pavilion-Laptop-15-cc1xx:41953/]
[rospy.init][INFO] 2020-01-31 17:20:18,691: ROS Slave URI: [http://itachi-HP-Pavilion-Laptop-15-cc1xx:41953/]
[rospy.impl.masterslave][INFO] 2020-01-31 17:20:18,691: _ready: http://itachi-HP-Pavilion-Laptop-15-cc1xx:41953/
[rospy.registration][INFO] 2020-01-31 17:20:18,692: Registering with master node http://localhost:11311
[xmlrpc][INFO] 2020-01-31 17:20:18,692: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2020-01-31 17:20:18,692: registering subscriber topic [/usb_cam/image_rect] type [sensor_msgs/Image] with master
[rospy.internal][INFO] 2020-01-31 17:20:18,695: topic[/usb_cam/image_rect] adding connection to [http://itachi-HP-Pavilion-Laptop-15-cc1xx:35837/], count 0
[rospy.init][INFO] 2020-01-31 17:20:18,791: registered with master
[rospy.rosout][INFO] 2020-01-31 17:20:18,792: initializing /rosout core topic
[rospy.rosout][INFO] 2020-01-31 17:20:18,796: connected to core topic /rosout
[rospy.simtime][INFO] 2020-01-31 17:20:18,798: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2020-01-31 17:20:19,048: topic[/rosout] adding connection to [/rosout], count 0
[rospy.core][INFO] 2020-01-31 17:20:43,260: signal_shutdown [signal-2]
[rospy.internal][INFO] 2020-01-31 17:20:43,265: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2020-01-31 17:20:43,266: topic[/usb_cam/image_rect] removing connection to http://itachi-HP-Pavilion-Laptop-15-cc1xx:35837/
[rospy.internal][WARNING] 2020-01-31 17:20:43,267: Unknown error initiating TCP/IP socket to itachi-HP-Pavilion-Laptop-15-cc1xx:42609 (http://itachi-HP-Pavilion-Laptop-15-cc1xx:35837/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
AttributeError: 'NoneType' object has no attribute 'buff_size'

[rospy.topics][ERROR] 2020-01-31 17:20:43,269: Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 326, in close
    c.close()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 838, in close
    self.socket.close()
AttributeError: 'NoneType' object has no attribute 'close'

[rospy.impl.masterslave][INFO] 2020-01-31 17:20:43,269: signal-2
[rospy.core][INFO] 2020-01-31 17:20:43,370: signal_shutdown [atexit]
