[rospy.client][INFO] 2020-01-31 16:31:32,868: init_node, name[/sr_determine_rois_9868_1580468492827], pid[9868]
[xmlrpc][INFO] 2020-01-31 16:31:32,869: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2020-01-31 16:31:32,869: Started XML-RPC server [http://itachi-HP-Pavilion-Laptop-15-cc1xx:34897/]
[rospy.init][INFO] 2020-01-31 16:31:32,869: ROS Slave URI: [http://itachi-HP-Pavilion-Laptop-15-cc1xx:34897/]
[rospy.impl.masterslave][INFO] 2020-01-31 16:31:32,869: _ready: http://itachi-HP-Pavilion-Laptop-15-cc1xx:34897/
[rospy.registration][INFO] 2020-01-31 16:31:32,870: Registering with master node http://localhost:11311
[xmlrpc][INFO] 2020-01-31 16:31:32,870: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2020-01-31 16:31:32,870: registering subscriber topic [/usb_cam/image_rect] type [sensor_msgs/Image] with master
[rospy.internal][INFO] 2020-01-31 16:31:32,873: topic[/usb_cam/image_rect] adding connection to [http://itachi-HP-Pavilion-Laptop-15-cc1xx:45585/], count 0
[rosout][ERROR] 2020-01-31 16:31:32,945: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7f24cb2dba70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 38, in image_callback
    cv2.putText(img_copy,block_names[i], (center_x, center_y), cv2.FONT_HERSHEY_COMPLEX_SMALL, 1, (255,255,255))
IndexError: list index out of range

[rosout][ERROR] 2020-01-31 16:31:32,962: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7f24cb2dba70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 38, in image_callback
    cv2.putText(img_copy,block_names[i], (center_x, center_y), cv2.FONT_HERSHEY_COMPLEX_SMALL, 1, (255,255,255))
IndexError: list index out of range

[rospy.init][INFO] 2020-01-31 16:31:32,970: registered with master
[rospy.rosout][INFO] 2020-01-31 16:31:32,970: initializing /rosout core topic
[rospy.rosout][INFO] 2020-01-31 16:31:32,973: connected to core topic /rosout
[rospy.simtime][INFO] 2020-01-31 16:31:32,975: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2020-01-31 16:31:33,190: topic[/rosout] adding connection to [/rosout], count 0
[rosout][ERROR] 2020-01-31 16:31:44,928: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7f24cb2dba70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 38, in image_callback
    cv2.putText(img_copy,block_names[i], (center_x, center_y), cv2.FONT_HERSHEY_COMPLEX_SMALL, 1, (255,255,255))
IndexError: list index out of range

[rosout][ERROR] 2020-01-31 16:31:44,952: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7f24cb2dba70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 38, in image_callback
    cv2.putText(img_copy,block_names[i], (center_x, center_y), cv2.FONT_HERSHEY_COMPLEX_SMALL, 1, (255,255,255))
IndexError: list index out of range

[rosout][ERROR] 2020-01-31 16:31:44,979: bad callback: <bound method sr_determine_rois.image_callback of <__main__.sr_determine_rois instance at 0x7f24cb2dba70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/itachi/catkin_ws/src/survey_and_rescue/scripts/srujan_image_proc5.py", line 38, in image_callback
    cv2.putText(img_copy,block_names[i], (center_x, center_y), cv2.FONT_HERSHEY_COMPLEX_SMALL, 1, (255,255,255))
IndexError: list index out of range

[rospy.core][INFO] 2020-01-31 16:33:50,049: signal_shutdown [signal-2]
[rospy.internal][INFO] 2020-01-31 16:33:50,052: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2020-01-31 16:33:50,053: topic[/usb_cam/image_rect] removing connection to http://itachi-HP-Pavilion-Laptop-15-cc1xx:45585/
[rospy.impl.masterslave][INFO] 2020-01-31 16:33:50,053: signal-2
[rospy.core][INFO] 2020-01-31 16:33:50,161: signal_shutdown [atexit]
